name: new_ecommerce
description: "A new Flutter project."
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_route: ^9.2.0
  dio: ^5.7.0
  dio_smart_retry: ^6.0.0
  duration: ^4.0.3
  flash: ^3.1.1
  flex_color_scheme: ^8.0.1
  flutter:
    sdk: flutter

  flutter_displaymode: ^0.6.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.2
  hive_ce_flutter: ^2.1.0
  icons_launcher: ^3.0.0
  internet_connection_checker_plus: ^2.5.2
  intl: ^0.19.0
  multiple_result: ^5.1.0
  path_provider: ^2.1.5
  platform_info: ^4.0.2
  responsive_framework:
    git: https://github.com/Shreemanarjun/ResponsiveFramework.git
  talker_dio_logger: ^4.5.1
  talker_flutter: ^4.4.0
  talker_riverpod_logger: ^4.5.1
  velocity_x: ^4.2.1
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  riverpod_lint: ^2.6.3
  riverpod_test: ^0.1.6
  very_good_analysis: ^6.0.0

  # Added for support WASM
dependency_overrides:
  flutter_secure_storage_web: ^2.0.0-beta.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/logo/
